- name: "copy files"
  hosts: all
  become: yes
  vars:
    source: /tmp/one.txt
    dest: /tmp/one.txt
  tasks:
    - name: "Copy file"
      copy:
        src: "{{source}}"
        dest: "{{dest}}"
        owner: igor
        group: root
        mode: 777   
